sudo: false
env:
  matrix:
  - DEBUG=True
  - DJANGO_SETTINGS_MODULE=representatives.tests.settings
language: python
python:
- '2.7'
install:
- pip install django
- pip install -e .
- wget https://github.com/political-memory/political_memory/archive/openshift.tar.gz
- tar xvzf openshift.tar.gz
- pip install -r political_memory-openshift/requirements.txt
script:
- django-admin migrate
- django-admin parltrack_import_representatives
before_deploy:
- django-admin dumpdata -o django-representatives-data.json representatives
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: g9RSaruNWpSdh8UYX4H9Q92m/tjU3Ly7TqU3e86cbEpPvNdrsT69DqauRhhaEjvrtj2opFrIwiQrOXDr0P4OTQg7ba3TchthFqNBccq7Ns0lBHKcIzjtu/sshRi/AQIKCSxYbw1+tKm6gQTO4NYaQ320g1QUkbalQlakxPm8ng8=
  file: django-representatives-data.json
  on:
    tags: false
    all_branches: true
