sudo: false
language: python
python:
  - "2.7"
install:
  - pip install django
  - pip install -e .
  - wget https://github.com/political-memory/political_memory/archive/master.tar.gz
  - tar xvzf master.tar.gz
script:
  - political_memory-master/manage.py migrate
  - political_memory-master/manage.py import_parltrack_representatives
