sudo: false
language: python
python:
  - "2.7"
install:
  - pip install django
  - pip install -e .
script:
  - test_project/manage.py migrate
  - test_project/manage.py import_representatives_from_compotista
